import { addDays, subDays, format } from 'date-fns'

const today = new Date()

export const DEMO_USERS = {
  // Admin
  '+77770000000': {
    id: 1,
    phone: '+77770000000',
    full_name: 'Ербол Асанов',
    username: 'admin',
    role: 'admin',
    is_staff: true,
    pppoe_login: 'erbol_admin',
    tariff: 'tariff-25mbps',
    tariff_price: 8500,
    tariff_speed: '25 Мбит/с',
    is_active_subscription: true,
    subscription_end: format(addDays(today, 18), 'yyyy-MM-dd'),
    password: 'admin123',
  },
  // Clients
  '+77771000000': {
    id: 2,
    phone: '+77771000000',
    full_name: 'Adik Seitkali',
    username: 'adik',
    role: 'client',
    is_staff: false,
    pppoe_login: 'adik',
    tariff: 'tariff-10mbps',
    tariff_price: 4500,
    tariff_speed: '10 Мбит/с',
    is_active_subscription: true,
    subscription_end: format(addDays(today, 20), 'yyyy-MM-dd'),
    password: 'client123',
  },
  '+77772000000': {
    id: 3,
    phone: '+77772000000',
    full_name: 'Salim Bekov',
    username: 'salim',
    role: 'client',
    is_staff: false,
    pppoe_login: 'salim',
    tariff: 'tariff-5mbps',
    tariff_price: 3000,
    tariff_speed: '5 Мбит/с',
    is_active_subscription: true,
    subscription_end: format(addDays(today, 5), 'yyyy-MM-dd'),
    password: 'client123',
  },
  '+77773000000': {
    id: 4,
    phone: '+77773000000',
    full_name: 'Huse Aliev',
    username: 'huse',
    role: 'client',
    is_staff: false,
    pppoe_login: 'huse',
    tariff: 'tariff-15mbps',
    tariff_price: 6000,
    tariff_speed: '15 Мбит/с',
    is_active_subscription: false,
    subscription_end: format(subDays(today, 2), 'yyyy-MM-dd'),
    password: 'client123',
  },
}

export const DEMO_PAYMENTS = [
  {
    id: 'pay-001',
    user: 2,
    user_name: 'Adik Seitkali',
    user_phone: '+77771000000',
    amount: '4500.00',
    period_months: 1,
    period_label: '1 месяц',
    status: 'paid',
    tariff: 'tariff-10mbps',
    extended_from: format(subDays(today, 30), 'yyyy-MM-dd'),
    extended_to: format(addDays(today, 20), 'yyyy-MM-dd'),
    discount_info: null,
    created_at: subDays(today, 30).toISOString(),
    paid_at: subDays(today, 30).toISOString(),
  },
  {
    id: 'pay-002',
    user: 2,
    user_name: 'Adik Seitkali',
    user_phone: '+77771000000',
    amount: '12555.00',
    period_months: 3,
    period_label: '3 месяца',
    status: 'paid',
    tariff: 'tariff-10mbps',
    extended_from: format(subDays(today, 120), 'yyyy-MM-dd'),
    extended_to: format(subDays(today, 30), 'yyyy-MM-dd'),
    discount_info: '−7%',
    created_at: subDays(today, 120).toISOString(),
    paid_at: subDays(today, 120).toISOString(),
  },
  {
    id: 'pay-003',
    user: 3,
    user_name: 'Salim Bekov',
    user_phone: '+77772000000',
    amount: '3000.00',
    period_months: 1,
    period_label: '1 месяц',
    status: 'paid',
    tariff: 'tariff-5mbps',
    extended_from: format(subDays(today, 25), 'yyyy-MM-dd'),
    extended_to: format(addDays(today, 5), 'yyyy-MM-dd'),
    discount_info: null,
    created_at: subDays(today, 25).toISOString(),
    paid_at: subDays(today, 25).toISOString(),
  },
  {
    id: 'pay-004',
    user: 4,
    user_name: 'Huse Aliev',
    user_phone: '+77773000000',
    amount: '15660.00',
    period_months: 3,
    period_label: '3 месяца',
    status: 'paid',
    tariff: 'tariff-15mbps',
    extended_from: format(subDays(today, 95), 'yyyy-MM-dd'),
    extended_to: format(subDays(today, 5), 'yyyy-MM-dd'),
    discount_info: '−7%',
    created_at: subDays(today, 95).toISOString(),
    paid_at: subDays(today, 95).toISOString(),
  },
  {
    id: 'pay-005',
    user: 2,
    user_name: 'Adik Seitkali',
    user_phone: '+77771000000',
    amount: '4500.00',
    period_months: 1,
    period_label: '1 месяц',
    status: 'pending',
    tariff: 'tariff-10mbps',
    extended_from: null,
    extended_to: null,
    discount_info: null,
    created_at: subDays(today, 1).toISOString(),
    paid_at: null,
  },
]

export const DEMO_CLIENTS = [
  {
    id: 2, phone: '+77771000000', full_name: 'Adik Seitkali', username: 'adik',
    pppoe_login: 'adik', pppoe_password: 'pass4291',
    tariff: 'tariff-10mbps', tariff_price: 4500, tariff_speed: '10 Мбит/с',
    is_active_subscription: true,
    subscription_end: format(addDays(today, 20), 'yyyy-MM-dd'),
    payment_count: 2,
    last_payment: { amount: '4500.00', paid_at: subDays(today, 30).toISOString() },
    created_at: subDays(today, 180).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 3, phone: '+77772000000', full_name: 'Salim Bekov', username: 'salim',
    pppoe_login: 'salim', pppoe_password: 'pass7832',
    tariff: 'tariff-5mbps', tariff_price: 3000, tariff_speed: '5 Мбит/с',
    is_active_subscription: true,
    subscription_end: format(addDays(today, 5), 'yyyy-MM-dd'),
    payment_count: 1,
    last_payment: { amount: '3000.00', paid_at: subDays(today, 25).toISOString() },
    created_at: subDays(today, 150).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 4, phone: '+77773000000', full_name: 'Huse Aliev', username: 'huse',
    pppoe_login: 'huse', pppoe_password: 'pass1147',
    tariff: 'tariff-15mbps', tariff_price: 6000, tariff_speed: '15 Мбит/с',
    is_active_subscription: false,
    subscription_end: format(subDays(today, 2), 'yyyy-MM-dd'),
    payment_count: 1,
    last_payment: { amount: '15660.00', paid_at: subDays(today, 95).toISOString() },
    created_at: subDays(today, 200).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 5, phone: '+77774000000', full_name: 'Arafat Nurov', username: 'arafat',
    pppoe_login: 'arafat', pppoe_password: 'pass5563',
    tariff: 'tariff-10mbps', tariff_price: 4500, tariff_speed: '10 Мбит/с',
    is_active_subscription: true,
    subscription_end: format(addDays(today, 28), 'yyyy-MM-dd'),
    payment_count: 3,
    last_payment: { amount: '4500.00', paid_at: subDays(today, 2).toISOString() },
    created_at: subDays(today, 250).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 6, phone: '+77775000000', full_name: 'Hakim Dzhaksybekov', username: 'hakim',
    pppoe_login: 'hakim', pppoe_password: 'pass9921',
    tariff: 'tariff-25mbps', tariff_price: 8500, tariff_speed: '25 Мбит/с',
    is_active_subscription: true,
    subscription_end: format(addDays(today, 12), 'yyyy-MM-dd'),
    payment_count: 4,
    last_payment: { amount: '8500.00', paid_at: subDays(today, 18).toISOString() },
    created_at: subDays(today, 300).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 7, phone: '+77776000000', full_name: 'Stalbek Ergashev', username: 'stalbek',
    pppoe_login: 'stalbek', pppoe_password: 'pass3374',
    tariff: 'tariff-10mbps', tariff_price: 4500, tariff_speed: '10 Мбит/с',
    is_active_subscription: true,
    subscription_end: format(addDays(today, 3), 'yyyy-MM-dd'),
    payment_count: 2,
    last_payment: { amount: '4500.00', paid_at: subDays(today, 27).toISOString() },
    created_at: subDays(today, 120).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 8, phone: '+77777000000', full_name: 'Erbol Askarov', username: 'erbol',
    pppoe_login: 'erbol', pppoe_password: 'pass6612',
    tariff: 'tariff-15mbps', tariff_price: 6000, tariff_speed: '15 Мбит/с',
    is_active_subscription: true,
    subscription_end: format(addDays(today, 18), 'yyyy-MM-dd'),
    payment_count: 5,
    last_payment: { amount: '6000.00', paid_at: subDays(today, 12).toISOString() },
    created_at: subDays(today, 365).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 9, phone: '+77778000000', full_name: 'Arli Bekzhanov', username: 'arli',
    pppoe_login: 'arli', pppoe_password: 'pass8845',
    tariff: 'tariff-5mbps', tariff_price: 3000, tariff_speed: '5 Мбит/с',
    is_active_subscription: false,
    subscription_end: format(subDays(today, 3), 'yyyy-MM-dd'),
    payment_count: 1,
    last_payment: { amount: '3000.00', paid_at: subDays(today, 33).toISOString() },
    created_at: subDays(today, 90).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 10, phone: '+77779000000', full_name: 'Muhit Suleimenov', username: 'muhit',
    pppoe_login: 'muhit', pppoe_password: 'pass2238',
    tariff: 'tariff-10mbps', tariff_price: 4500, tariff_speed: '10 Мбит/с',
    is_active_subscription: true,
    subscription_end: format(addDays(today, 25), 'yyyy-MM-dd'),
    payment_count: 3,
    last_payment: { amount: '4500.00', paid_at: subDays(today, 5).toISOString() },
    created_at: subDays(today, 200).toISOString(),
    updated_at: new Date().toISOString(),
  },
]

// Build monthly revenue data (last 6 months)
function buildMonthlyChart() {
  const months = []
  for (let i = 5; i >= 0; i--) {
    const d = new Date(today.getFullYear(), today.getMonth() - i, 1)
    const monthStr = format(d, 'yyyy-MM')
    const total = 15000 + Math.random() * 50000
    months.push({ month: monthStr, total: Math.round(total), count: Math.floor(total / 5000) })
  }
  return months
}

export const DEMO_STATISTICS = {
  revenue: { today: 4500, week: 31500, month: 127350 },
  clients: { total: 9, active: 7, inactive: 2, expiring_soon: 3 },
  charts: {
    monthly: buildMonthlyChart(),
    daily: [],
  },
  tariff_distribution: [
    { tariff: 'tariff-10mbps', count: 4 },
    { tariff: 'tariff-15mbps', count: 2 },
    { tariff: 'tariff-5mbps', count: 2 },
    { tariff: 'tariff-25mbps', count: 1 },
  ],
}
